# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiticomp', '0003_auto_20180127_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='comppackage',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
