# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiticomp', '0004_comppackage_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comppackage',
            name='num_family',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
