# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiticomp', '0005_auto_20180129_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='comppackage',
            name='issue',
            field=models.TextField(blank=True),
        ),
    ]
