# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiticomp', '0006_comppackage_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='comppackage',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comppackage',
            name='tax_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
