# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haiticomp', '0007_auto_20180430_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompPackageRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haiticomp.CompPackage')),
            ],
        ),
    ]
