# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('haiticomp', '0008_comppackagerevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='comppackage',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comppackagerevision',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='comppackagerevision',
            name='num_family',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comppackagerevision',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
