# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiticomp', '0009_auto_20180503_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='comppackagerevision',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
