# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiticomp', '0011_auto_20180503_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
